// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCitas.Infraestructura.Persistencia;

#nullable disable

namespace SistemaCitas.Infraestructura.Migrations
{
    [DbContext(typeof(SistemaCitasDbContext))]
    partial class SistemaCitasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Cita", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrgencyDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.ToTable("Citas");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.CondicionMedica", b =>
                {
                    b.Property<int>("ConditionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConditionId");

                    b.HasIndex("PatientId");

                    b.ToTable("CondicionesMedicas");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Paciente", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.PuntuacionPrioridad", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CalculatedScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ScoreId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("PuntuacionesPrioridad");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Cita", b =>
                {
                    b.HasOne("SistemaCitas.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.CondicionMedica", b =>
                {
                    b.HasOne("SistemaCitas.Dominio.Entidades.Paciente", "Paciente")
                        .WithMany("CondicionesMedicas")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.PuntuacionPrioridad", b =>
                {
                    b.HasOne("SistemaCitas.Dominio.Entidades.Cita", "Cita")
                        .WithOne("PuntuacionPrioridad")
                        .HasForeignKey("SistemaCitas.Dominio.Entidades.PuntuacionPrioridad", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Cita", b =>
                {
                    b.Navigation("PuntuacionPrioridad");
                });

            modelBuilder.Entity("SistemaCitas.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("CondicionesMedicas");
                });
#pragma warning restore 612, 618
        }
    }
}
